// Generated by CoffeeScript 1.9.3
(function() {
  var music;

  music = angular.module('music', []);

  music.controller('filesCtrl', function($scope) {
    $scope.fileList = 'hello world';
    return $scope.go = function() {
      return console.log("GO!");
    };
  });

}).call(this);
