// Generated by CoffeeScript 1.9.3
(function() {
  (function() {
    var filesModel;
    filesModel = function() {
      var directive, link;
      link = function(scope, elem, attrs) {};
      directive = {
        link: link,
        restrict: 'A'
      };
      return directive;
    };
    return angular.module('music').directive('filesModel', filesModel);
  })();

}).call(this);
