// Generated by CoffeeScript 1.9.3
(function() {
  var controller, mainCtrl, template;

  template = require('../views/main');

  mainCtrl = function($scope) {
    return $scope.message = template;
  };

  controller = function(angular) {
    return (angular.module('music')).controller('mainCtrl', mainCtrl);
  };

  module.exports = controller;

}).call(this);
