// Generated by CoffeeScript 1.9.3
(function() {
  var Template, contents, fs;

  fs = require('fs');

  Template = './app/partials/helloworld.html';

  contents = (fs.readFileSync(Template)).toString();

  module.exports = contents;

}).call(this);
